script:
  - "npm test"

language: node_js

node_js: "0.12.0"

cache:
  directories:
    - node_modules
matrix:
  fast_finish: true
  include:
    - node_js: "0.12"
      env: COVERAGE=true

  allow_failures:
    - node_js: "0.11"
      env: COVERAGE=true